version: '3.8'

services:
  knowledge-crawler:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
      - ../assets:/app/assets
    environment:
      - EMBEDDING_MODEL=local
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama
    networks:
      - crawler-network

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - crawler-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama-data:

networks:
  crawler-network:
    driver: bridge